# Generated by Django 5.2.8 on 2026-08-08 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities_app', '0001_initial'),
        ('matching_app', '0001_initial'),
        ('shifts_app', '0001_initial'),
        ('workers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='facilities_app.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='facilities_app.facility')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts_app.shift')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matching_app.shiftapplication')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='workers_app.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerPayoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_connect_account_id', models.CharField(blank=True, max_length=255)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_profile', to='workers_app.workerprofile')),
            ],
        ),
    ]
