# Generated by Django 5.2.8 on 2026-08-08 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts_app', '0001_initial'),
        ('workers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No-show'), ('CANCELLED', 'Cancelled')], default='APPLIED', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shifts_app.shift')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='workers_app.workerprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shift', 'worker'), name='unique_application_per_worker_per_shift')],
            },
        ),
    ]
