# Generated by Django 5.2.8 on 2026-08-08 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('FACILITY_TO_WORKER', 'Facility rates Worker'), ('WORKER_TO_FACILITY', 'Worker rates Facility')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='matching_app.shiftapplication')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application', 'direction'), name='one_review_per_direction_per_application')],
            },
        ),
    ]
