# Generated by Django 5.2.8 on 2026-08-08 03:20

import django.db.models.deletion
import workers_app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('home_address', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='worker_photos/')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('completed_shifts_count', models.PositiveIntegerField(default=0)),
                ('no_show_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('FORKLIFT_I', 'Forklift — Class I (Electric Motor Rider)'), ('FORKLIFT_II', 'Forklift — Class II (Electric Motor Narrow Aisle)'), ('FORKLIFT_III', 'Forklift — Class III (Electric Motor Hand/Rider)'), ('FORKLIFT_IV', 'Forklift — Class IV (Internal Combustion, Cushion Tire)'), ('FORKLIFT_V', 'Forklift — Class V (Internal Combustion, Pneumatic Tire)'), ('FORKLIFT_VI', 'Forklift — Class VI (Electric/IC Tractor)'), ('FORKLIFT_VII', 'Forklift — Class VII (Rough Terrain)'), ('OSHA_10', 'OSHA 10-Hour General Industry'), ('OSHA_30', 'OSHA 30-Hour General Industry'), ('GENERAL', 'General Labor (no certification required)')], max_length=30)),
                ('document', models.FileField(upload_to='certifications/', validators=[workers_app.validators.validate_cert_document])),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certifications', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='workers_app.workerprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
