# Generated by Django 5.2.8 on 2026-08-08 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('FORKLIFT_I', 'Forklift — Class I (Electric Motor Rider)'), ('FORKLIFT_II', 'Forklift — Class II (Electric Motor Narrow Aisle)'), ('FORKLIFT_III', 'Forklift — Class III (Electric Motor Hand/Rider)'), ('FORKLIFT_IV', 'Forklift — Class IV (Internal Combustion, Cushion Tire)'), ('FORKLIFT_V', 'Forklift — Class V (Internal Combustion, Pneumatic Tire)'), ('FORKLIFT_VI', 'Forklift — Class VI (Electric/IC Tractor)'), ('FORKLIFT_VII', 'Forklift — Class VII (Rough Terrain)'), ('OSHA_10', 'OSHA 10-Hour General Industry'), ('OSHA_30', 'OSHA 30-Hour General Industry'), ('GENERAL', 'General Labor (no certification required)')], max_length=30)),
                ('required_cert', models.CharField(choices=[('FORKLIFT_I', 'Forklift — Class I (Electric Motor Rider)'), ('FORKLIFT_II', 'Forklift — Class II (Electric Motor Narrow Aisle)'), ('FORKLIFT_III', 'Forklift — Class III (Electric Motor Hand/Rider)'), ('FORKLIFT_IV', 'Forklift — Class IV (Internal Combustion, Cushion Tire)'), ('FORKLIFT_V', 'Forklift — Class V (Internal Combustion, Pneumatic Tire)'), ('FORKLIFT_VI', 'Forklift — Class VI (Electric/IC Tractor)'), ('FORKLIFT_VII', 'Forklift — Class VII (Rough Terrain)'), ('OSHA_10', 'OSHA 10-Hour General Industry'), ('OSHA_30', 'OSHA 30-Hour General Industry'), ('GENERAL', 'General Labor (no certification required)')], default='GENERAL', help_text='Certification a worker must hold VERIFIED to claim this shift.', max_length=30)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('headcount_needed', models.PositiveIntegerField(default=1)),
                ('headcount_filled', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='OPEN', max_length=15)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('auto_accept', models.BooleanField(default=False, help_text='Confirm applicants automatically without facility review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='facilities_app.facilitylocation')),
            ],
            options={
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['status'], name='shifts_app__status_c36a22_idx'), models.Index(fields=['start_datetime'], name='shifts_app__start_d_0579cc_idx'), models.Index(fields=['location'], name='shifts_app__locatio_d42840_idx')],
            },
        ),
    ]
